# The following code is an evolution of plotting code from wiggleplotr,
# generated by Claude Code and using v1.35.2 of wiggleplotr code base

# Plot the transcripts behind splicelogic events, with the event exons
# highlighted. The intron rescaling follows the transcript plots in
# wiggleplotr.

utils::globalVariables(c(
  "tx_id", "estimate", "event_tx_id", "event_estimate", "event_type",
  "gene_id", "tx_pair", "row_y", "direction", "tx_label", "fill_key",
  "fill_keys", "event_label", "is_event", "plot_start", "plot_end",
  "joint_start", "joint_plot_start", "x", "xend", "lfc", "annot", "width",
  "strand", "start", "end", "tss_x", "arrow_dir", "y", "point", "u", "v",
  "edge", "vertex", "inside", "poly_id", "step", "type_i", "lo", "hi"
))

#' Default fill colours for splicelogic event types
#'
#' One pastel colour per `event_type` returned by the `find_*()` functions,
#' chosen together with the soft blue and red [plot_transcripts()] uses for
#' the up- and down-regulated transcripts, so the ten stay as far apart as
#' pastels allow, including under protanopia and deuteranopia. Pastels leave
#' less room between colours than saturated ones, which is why event exons
#' are also outlined and labelled with their type.
#'
#' @return A character vector of colours, named by event type.
#'
#' @examples
#' event_palette()
#'
#' @export
event_palette <- function() {
  c(
    se = "#FFB38A",
    ie = "#74B9B7",
    mxe = "#AAA7F1",
    ri = "#DDE699",
    a5ss = "#7BE8FE",
    a3ss = "#FFC4D6",
    atss = "#99D6A8",
    ates = "#81bc5c"
  )
}

#' @noRd
check_ggplot2 <- function() {
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop(
      "Package 'ggplot2' is required for plotting. ",
      "Install with: install.packages('ggplot2')"
    )
  }
}

#' Check that events look like the output of a find_*() function
#' @noRd
check_plot_events <- function(events, required = character(0)) {
  if (!methods::is(events, "GRanges")) {
    stop("'events' must be a GRanges returned by a find_*() function.")
  }
  # a finder with no hits returns a bare GRanges(), without any mcols
  if (length(events) == 0L) {
    stop("'events' has no rows.")
  }
  required <- c(
    "tx_id", "estimate", "event_tx_id", "event_estimate", "event_type",
    required
  )
  missing_cols <- setdiff(required, names(GenomicRanges::mcols(events)))
  if (length(missing_cols) > 0) {
    stop(
      "Missing metadata columns in 'events': ",
      paste(missing_cols, collapse = ", ")
    )
  }
}

#' Check the exons to draw the transcripts from
#' @noRd
check_plot_exons <- function(exons) {
  has_tx_id <- "tx_id" %in% names(GenomicRanges::mcols(exons))
  if (!methods::is(exons, "GRanges") || !has_tx_id) {
    stop(
      "'exons' must be a flat GRanges of exons with a 'tx_id' column, ",
      "e.g. the GRanges passed to the find_*() functions."
    )
  }
}

#' Check that a panel holds a single gene
#'
#' Several genes on one panel would have the distance between them collapsed
#' like an intron and read as one gene, even on the same chromosome. The gene
#' is taken from `events` and, when it has a `gene_id` column, from the exons
#' of the transcripts being drawn.
#' @noRd
check_single_gene <- function(events, panel_exons) {
  genes <- c(
    if ("gene_id" %in% names(GenomicRanges::mcols(events))) events$gene_id,
    if ("gene_id" %in% names(GenomicRanges::mcols(panel_exons))) {
      panel_exons$gene_id
    }
  )
  genes <- unique(as.character(genes))
  if (length(genes) > 1L) {
    stop(
      "'events' spans ", length(genes), " genes (",
      paste(utils::head(genes, 3), collapse = ", "),
      if (length(genes) > 3L) ", ..." else "",
      "); plot_transcripts() draws one gene. Subset 'events' to a single ",
      "gene first, e.g. dplyr::filter(events, gene_id == \"", genes[1],
      "\"), or use plot_transcripts_by_gene() for one plot per gene."
    )
  }
}

#' Every transcript on either side of an event, one row each
#'
#' Rows are ordered with the most up-regulated transcript at the top of the
#' panel, and spaced wider than the exon boxes to leave room for the
#' transcript and event labels.
#' @noRd
transcript_rows <- function(events) {
  events_tbl <- tibble::as_tibble(events)
  dplyr::bind_rows(
    events_tbl |>
      dplyr::select(tx_id, estimate),
    events_tbl |>
      dplyr::select(tx_id = event_tx_id, estimate = event_estimate)
  ) |>
    # estimates from prepare_exons_by_partition() are integer, which the
    # "%+.2f" label format rejects
    dplyr::mutate(
      tx_id = as.character(tx_id),
      estimate = as.numeric(estimate)
    ) |>
    dplyr::distinct(tx_id, .keep_all = TRUE) |>
    dplyr::arrange(dplyr::desc(estimate)) |>
    dplyr::mutate(
      row_y = rev(seq_len(dplyr::n())) * 1.5,
      direction = dplyr::if_else(estimate < 0, "down", "up")
    )
}

#' y-axis limits shared by plot_transcripts() and plot_transcript_lfc()
#'
#' Fixed from the rows rather than left to ggplot2, which would size each
#' plot by its own labels, so the two line up when placed side by side.
#' @noRd
row_limits <- function(tx_rows) {
  c(min(tx_rows$row_y) - 1.1, max(tx_rows$row_y) + 1.1)
}

#' Plot coordinates for every exon of a set of transcripts
#'
#' Exons are placed by the union of all exons in the panel. With
#' `rescale_introns = TRUE` each gap in that union is shortened to
#' `new_intron_length`, and an exon keeps its offset within the union range
#' that contains it, so shared boundaries stay aligned across transcripts.
#'
#' @return A list with `exons` (a tibble with `tx_id`, `strand`, `start`,
#'   `end`, `plot_start` and `plot_end`), the x-axis `limits` and `xlabel`.
#' @noRd
layout_transcripts <- function(exons, rescale_introns, new_intron_length,
                               flanking_length) {
  stopifnot(length(flanking_length) == 2L)
  chr <- unique(as.character(GenomicRanges::seqnames(exons)))
  if (length(chr) > 1L) {
    stop("The transcripts are on more than one chromosome.")
  }

  joint <- GenomicRanges::reduce(exons, ignore.strand = TRUE)
  joint <- if (rescale_introns) {
    joint |>
      dplyr::mutate(
        joint_start = start,
        joint_plot_start = flanking_length[1] +
          cumsum(dplyr::lag(width, default = 0L)) +
          (seq_along(start) - 1L) * new_intron_length
      )
  } else {
    joint |>
      dplyr::mutate(joint_start = start, joint_plot_start = start)
  }

  exons_tbl <- exons |>
    plyranges::join_overlap_inner_within(joint) |>
    tibble::as_tibble() |>
    dplyr::mutate(
      tx_id = as.character(tx_id),
      strand = as.character(strand),
      plot_start = joint_plot_start + start - joint_start,
      plot_end = joint_plot_start + end - joint_start
    ) |>
    dplyr::select(tx_id, strand, start, end, plot_start, plot_end)

  if (rescale_introns) {
    limits <- c(0, max(exons_tbl$plot_end) + flanking_length[2])
    xlabel <- "Distance from region start (bp)"
  } else {
    limits <- c(
      min(exons_tbl$plot_start) - flanking_length[1],
      max(exons_tbl$plot_end) + flanking_length[2]
    )
    xlabel <- paste("Chromosome", chr, "position (bp)")
  }
  list(exons = exons_tbl, limits = limits, xlabel = xlabel)
}

#' The event exons, one row per exon
#'
#' Events are matched to exons on transcript and coordinates, which a finder
#' copies unchanged from the exons it was given. An exon can carry several
#' event types (e.g. a5ss and a3ss when both boundaries moved), so they are
#' collapsed into one label. `fill_key` is the first type, the colour the box
#' is filled with; `fill_keys` keeps all of them, which [exon_stripes()] uses
#' to stripe the box with the ones the fill leaves out.
#' @noRd
event_exons <- function(events, layout_exons) {
  events_tbl <- tibble::as_tibble(events) |>
    dplyr::mutate(tx_id = as.character(tx_id)) |>
    dplyr::filter(tx_id %in% layout_exons$tx_id) |>
    dplyr::select(tx_id, start, end, event_type)

  n_unmatched <- events_tbl |>
    dplyr::anti_join(layout_exons, by = c("tx_id", "start", "end")) |>
    nrow()
  if (n_unmatched > 0L) {
    warning(
      n_unmatched, " event exon(s) had no match in 'exons'; ",
      "they will not be highlighted."
    )
  }

  events_tbl |>
    dplyr::group_by(tx_id, start, end) |>
    dplyr::summarise(
      event_label = toupper(paste(sort(unique(event_type)), collapse = "+")),
      fill_keys = list(sort(unique(as.character(event_type)))),
      fill_key = fill_keys[[1]][1],
      .groups = "drop"
    )
}

#' Clip a convex polygon by the half plane `fn(u, v) >= 0`
#'
#' Sutherland-Hodgman: walk the edges, keep every vertex inside the half
#' plane, and add the crossing point wherever an edge leaves or enters it.
#' The vertices have to stay in drawing order, so the edges are indexed and
#' the two candidate points per edge interleaved, rather than appended in a
#' loop.
#'
#' @return A tibble of `u` / `v` vertices, possibly empty.
#' @noRd
clip_half_plane <- function(poly, fn) {
  n <- nrow(poly)
  if (n == 0L) {
    return(poly)
  }
  nxt <- c(seq_len(n)[-1], 1L)
  d <- fn(poly$u, poly$v)
  inside <- d >= 0
  # NaN where an edge lies in the boundary line, dropped with the row below
  frac <- d / (d - d[nxt])

  tibble::tibble(
    edge = rep(seq_len(n), 2L),
    vertex = rep(c(1L, 2L), each = n),
    inside = c(inside, inside != inside[nxt]),
    u = c(poly$u, poly$u + frac * (poly$u[nxt] - poly$u)),
    v = c(poly$v, poly$v + frac * (poly$v[nxt] - poly$v))
  ) |>
    dplyr::filter(inside) |>
    dplyr::arrange(edge, vertex) |>
    dplyr::select(u, v)
}

#' One diagonal band of an exon box
#'
#' The box `[u1, u2] x [v1, v2]` clipped to the band `lo <= v - u <= hi`.
#' @noRd
clip_stripe <- function(u1, u2, v1, v2, lo, hi) {
  tibble::tibble(u = c(u1, u2, u2, u1), v = c(v1, v1, v2, v2)) |>
    clip_half_plane(function(u, v) (v - u) - lo) |>
    clip_half_plane(function(u, v) hi - (v - u))
}

#' Diagonal stripes for exons called as more than one event type
#'
#' An exon can be called as several types at once, e.g. an a5ss and an a3ss
#' when both of its boundaries moved. The box is filled with the first type
#' and striped with the others, so no type is hidden behind another and the
#' legend entry for each of them still points at something on the plot.
#'
#' The stripes are one global set of diagonal bands, cut into `n` sub-bands
#' of equal width, one per type of the exon. The first sub-band is left to
#' the fill of the box and the rest are drawn over it, so a two-type exon
#' comes out half filled and half striped. Being global, the bands line up
#' between exons on the same diagonal.
#'
#' Position is in plot units, where x is bp and y is rows, so a 45 degree
#' slope there would depend on the gene. The bands are built in panel
#' fractions instead (`u`, `v`), which makes them diagonal on the page, and
#' `period` — the width of one full set of bands, also a panel fraction —
#' keeps every stripe the same width whatever the exon.
#'
#' @return A tibble of polygon vertices with `poly_id`, `x`, `y` and
#'   `fill_key`, empty when no exon carries more than one type.
#' @noRd
exon_stripes <- function(rects, limits, y_limits, half_height,
                         period = 0.05) {
  empty <- tibble::tibble(
    poly_id = character(0), x = numeric(0), y = numeric(0),
    fill_key = character(0)
  )
  multi <- rects |>
    dplyr::filter(is_event, lengths(fill_keys) > 1L)
  if (nrow(multi) == 0L) {
    return(empty)
  }
  x_range <- diff(limits)
  y_range <- diff(y_limits)

  bands <- lapply(seq_len(nrow(multi)), function(i) {
    types <- multi$fill_keys[[i]]
    n_types <- length(types)
    u1 <- (multi$plot_start[i] - limits[1]) / x_range
    u2 <- (multi$plot_end[i] - limits[1]) / x_range
    v1 <- (multi$row_y[i] - half_height - y_limits[1]) / y_range
    v2 <- (multi$row_y[i] + half_height - y_limits[1]) / y_range
    # v - u is lowest in the bottom right corner of the box and highest in
    # the top left one, so these are the band sets the box can reach
    steps <- seq(floor((v1 - u2) / period), floor((v2 - u1) / period))

    band_tbl <- tibble::tibble(
      step = rep(steps, each = n_types - 1L),
      type_i = rep(seq_len(n_types)[-1], times = length(steps))
    ) |>
      dplyr::mutate(
        lo = step * period + (type_i - 1L) * period / n_types,
        hi = lo + period / n_types,
        fill_key = types[type_i],
        poly_id = paste(
          multi$tx_id[i], multi$start[i], multi$end[i], step, type_i,
          sep = ":"
        )
      )

    # one polygon per band, each clipped on its own: a tibble cannot hold
    # them together, as a band keeps between zero and six vertices
    lapply(seq_len(nrow(band_tbl)), function(j) {
      clip_stripe(u1, u2, v1, v2, band_tbl$lo[j], band_tbl$hi[j]) |>
        dplyr::mutate(
          poly_id = band_tbl$poly_id[j],
          x = limits[1] + u * x_range,
          y = y_limits[1] + v * y_range,
          fill_key = band_tbl$fill_key[j]
        ) |>
        dplyr::select(poly_id, x, y, fill_key)
    }) |>
      dplyr::bind_rows()
  })

  dplyr::bind_rows(c(list(empty), bands)) |>
    # a band can miss the box entirely, or touch it in a single corner
    dplyr::group_by(poly_id) |>
    dplyr::filter(dplyr::n() >= 3L) |>
    dplyr::ungroup()
}

#' Bent arrows marking where each transcript starts and which way it runs
#'
#' Each arrow starts on the top edge of the first exon, at the transcription
#' start (its left edge on "+", its right edge on "-"), rises `rise`, then
#' runs in the direction of transcription for `run_fraction` of the panel
#' width. Unstranded ("*") transcripts get no arrow.
#'
#' The rise is in rows and the run in bp, so the two legs can only be matched
#' approximately: 1.1% of the panel width is as long as half an exon box at
#' usual figure proportions, where a panel with more rows is drawn taller.
#'
#' @return A tibble of path points, three per transcript, in drawing order.
#' @noRd
tss_arrows <- function(layout_exons, tx_rows, limits, base, rise,
                       run_fraction = 0.011) {
  run <- run_fraction * diff(limits)
  first_exons <- layout_exons |>
    dplyr::filter(strand %in% c("+", "-")) |>
    dplyr::group_by(tx_id) |>
    # first exon in transcription order: leftmost on "+", rightmost on "-"
    dplyr::slice_min(
      dplyr::if_else(strand == "-", -plot_end, plot_start),
      n = 1, with_ties = FALSE
    ) |>
    dplyr::ungroup() |>
    dplyr::left_join(
      tx_rows |>
        dplyr::select(tx_id, row_y),
      by = "tx_id"
    ) |>
    dplyr::mutate(
      arrow_dir = dplyr::if_else(strand == "-", -1, 1),
      tss_x = dplyr::if_else(strand == "-", plot_end, plot_start)
    )

  dplyr::bind_rows(
    first_exons |>
      dplyr::mutate(point = 1L, x = tss_x, y = row_y + base),
    first_exons |>
      dplyr::mutate(point = 2L, x = tss_x, y = row_y + base + rise),
    first_exons |>
      dplyr::mutate(
        point = 3L, x = tss_x + arrow_dir * run, y = row_y + base + rise
      )
  ) |>
    dplyr::arrange(tx_id, point) |>
    dplyr::select(tx_id, point, x, y)
}

#' Plot the transcripts involved in splicelogic events
#'
#' Draws one row per transcript appearing in `tx_id` or `event_tx_id` of
#' `events`. Transcripts are coloured by the sign of their estimate (blue when
#' positive, red when negative), and the exons called as events are filled by
#' event type, outlined, and labelled with the type. An exon called as several
#' types at once, e.g. an a5ss and an a3ss when both of its boundaries moved,
#' is filled with the first type and striped diagonally with the others. A
#' bent arrow over the first exon marks where each transcript starts and which
#' way it runs.
#'
#' All events passed in are drawn on one panel, so they must come from a
#' single gene; events from several genes are an error. Subset first, or use
#' [plot_transcripts_by_gene()] for one plot per gene and
#' [plot_transcripts_by_pair()] for one plot per transcript pair. A single
#' event, e.g. `plot_transcripts(events[1], exons)`, draws its two transcripts.
#'
#' A per-transcript value such as a fold change is drawn separately by
#' [plot_transcript_lfc()]. Given the same `events`, the two plots share
#' their row order and y limits, so they line up side by side.
#'
#' @param events A GRanges returned by [find_all_events()] or any `find_*()`
#'   function.
#' @param exons A flat GRanges of exons with a `tx_id` column holding every
#'   transcript in `events`, e.g. the preprocessed GRanges the events were
#'   found in.
#' @param title Plot title. Default `NULL`.
#' @param up_color,down_color Colours for transcripts with a positive and a
#'   negative estimate.
#' @param event_colors Named vector mapping event type to fill colour.
#'   Default [event_palette()].
#' @param unknown_color Fill for event types absent from `event_colors`.
#' @param rescale_introns Whether gaps between exons are shortened to
#'   `new_intron_length`. Default `TRUE`.
#' @param new_intron_length Length (bp) of each gap after rescaling.
#'   Default `50`.
#' @param flanking_length Length (bp) of the region drawn before the first
#'   and after the last exon. Default `c(50, 50)`.
#' @param transcript_label Whether to print the transcript id and estimate
#'   above each row. Default `TRUE`.
#' @param label_events Whether to print the event type below each event exon.
#'   Default `TRUE`.
#' @param stripe_multi_events Whether an exon called as several event types is
#'   striped with the types its fill leaves out. Default `TRUE`; `FALSE` fills
#'   it with the first type alone, and drops the others from the legend.
#' @param label_size Size of the event labels. Default `2.6`.
#' @param legend Whether to draw the fill legend. Default `TRUE`.
#' @param tx_annot Optional character vector named by transcript id, appended
#'   to that transcript's label (e.g. novel status). Transcripts not named in
#'   it keep the plain label.
#'
#' @return A `ggplot` object.
#'
#' @examples
#' # one gene: "down" has three exons, "up" skips the middle one
#' exons <- data.frame(
#'   seqnames = "chr1",
#'   start = c(1, 201, 401, 1, 401),
#'   end = c(100, 300, 500, 100, 500),
#'   strand = "+",
#'   gene_id = "g1",
#'   tx_id = c("down", "down", "down", "up", "up"),
#'   exon_rank = c(1, 2, 3, 1, 2),
#'   estimate = c(-1, -1, -1, 1, 1)
#' ) |>
#'   plyranges::as_granges() |>
#'   preprocess(coef_col = "estimate")
#'
#' events <- find_all_events(exons, verbose = FALSE)
#'
#' if (requireNamespace("ggplot2", quietly = TRUE)) {
#'   plot_transcripts(events, exons)
#' }
#'
#' @export
plot_transcripts <- function(
  events,
  exons,
  title = NULL,
  up_color = "#2b6af4",
  down_color = "#d6372c",
  event_colors = event_palette(),
  unknown_color = "#999999",
  rescale_introns = TRUE,
  new_intron_length = 50,
  flanking_length = c(50, 50),
  transcript_label = TRUE,
  label_events = TRUE,
  label_size = 2.6,
  legend = TRUE,
  tx_annot = NULL,
  stripe_multi_events = TRUE
) {
  check_ggplot2()
  check_plot_events(events)
  check_plot_exons(exons)

  tx_rows <- transcript_rows(events)
  # taken before any transcript is dropped, to stay aligned with
  # plot_transcript_lfc(), which never sees the exons
  y_limits <- row_limits(tx_rows)
  missing_tx <- setdiff(tx_rows$tx_id, as.character(exons$tx_id))
  if (length(missing_tx) > 0L) {
    warning(
      "Dropping transcript(s) absent from 'exons': ",
      paste(missing_tx, collapse = ", ")
    )
    tx_rows <- tx_rows |>
      dplyr::filter(!tx_id %in% missing_tx)
  }
  if (nrow(tx_rows) == 0L) {
    stop("None of the event transcripts are present in 'exons'.")
  }

  panel_tx <- tx_rows$tx_id
  panel_exons <- exons |>
    dplyr::filter(tx_id %in% panel_tx)
  check_single_gene(events, panel_exons)
  layout <- panel_exons |>
    layout_transcripts(rescale_introns, new_intron_length, flanking_length)

  tx_rows <- tx_rows |>
    dplyr::mutate(
      annot = if (is.null(tx_annot)) NA_character_ else unname(tx_annot[tx_id]),
      tx_label = paste0(
        tx_id, "  (", sprintf("%+.2f", estimate), ")",
        dplyr::if_else(is.na(annot), "", paste0("  ", annot))
      )
    )

  # exon boxes span row_y +/- exon_half_height. the strand arrow sits on the
  # top edge of the first exon, and the transcript label above the arrow
  exon_half_height <- 0.22

  rects <- layout$exons |>
    dplyr::left_join(
      event_exons(events, layout$exons),
      by = c("tx_id", "start", "end")
    ) |>
    dplyr::left_join(
      tx_rows |>
        dplyr::select(tx_id, row_y, direction),
      by = "tx_id"
    ) |>
    dplyr::mutate(
      is_event = !is.na(fill_key),
      fill_key = dplyr::coalesce(fill_key, direction)
    )

  stripes <- rects |>
    # a scalar FALSE empties the layer without taking it out of the plot, so
    # the layer order does not depend on the argument
    dplyr::filter(stripe_multi_events) |>
    exon_stripes(layout$limits, y_limits, exon_half_height)

  # the legend covers what is drawn, so a type only striped onto an exon is
  # in it, and one striping was asked not to draw is not
  drawn_keys <- unique(c(rects$fill_key, stripes$fill_key))
  palette <- c(event_colors, up = up_color, down = down_color)
  unknown_types <- setdiff(drawn_keys, names(palette))
  palette <- c(
    palette,
    stats::setNames(rep(unknown_color, length(unknown_types)), unknown_types)
  )
  present <- intersect(names(palette), drawn_keys)
  breaks <- c(
    intersect(c("up", "down"), present),
    setdiff(present, c("up", "down"))
  )
  legend_labels <- dplyr::case_match(
    breaks,
    "up" ~ "up (estimate > 0)",
    "down" ~ "down (estimate < 0)",
    .default = toupper(breaks)
  )

  tx_lines <- rects |>
    dplyr::group_by(tx_id, row_y, direction) |>
    dplyr::summarise(
      x = min(plot_start), xend = max(plot_end), .groups = "drop"
    ) |>
    dplyr::left_join(
      tx_rows |>
        dplyr::select(tx_id, tx_label),
      by = "tx_id"
    )

  axis_breaks <- pretty(layout$limits)
  axis_breaks <- axis_breaks[
    axis_breaks >= layout$limits[1] & axis_breaks <= layout$limits[2]
  ]

  p <- ggplot2::ggplot() +
    ggplot2::geom_segment(
      data = tx_lines,
      ggplot2::aes(
        x = x, xend = xend, y = row_y, yend = row_y, colour = direction
      ),
      linewidth = 0.4,
      show.legend = FALSE
    ) +
    ggplot2::geom_rect(
      data = dplyr::filter(rects, !is_event),
      ggplot2::aes(
        xmin = plot_start, xmax = plot_end,
        ymin = row_y - exon_half_height, ymax = row_y + exon_half_height,
        fill = fill_key
      )
    ) +
    ggplot2::geom_rect(
      data = dplyr::filter(rects, is_event),
      ggplot2::aes(
        xmin = plot_start, xmax = plot_end,
        ymin = row_y - exon_half_height, ymax = row_y + exon_half_height,
        fill = fill_key
      )
    ) +
    # stripes for the types the fill leaves out, then the outline over them:
    # a stripe is clipped to the box, so it would eat into a border drawn
    # with the fill
    ggplot2::geom_polygon(
      data = stripes,
      ggplot2::aes(x = x, y = y, group = poly_id, fill = fill_key)
    ) +
    ggplot2::geom_rect(
      data = dplyr::filter(rects, is_event),
      ggplot2::aes(
        xmin = plot_start, xmax = plot_end,
        ymin = row_y - exon_half_height, ymax = row_y + exon_half_height
      ),
      fill = NA,
      colour = "grey15",
      linewidth = 0.3
    ) +
    ggplot2::scale_fill_manual(
      values = palette, breaks = breaks, labels = legend_labels, name = NULL
    ) +
    ggplot2::scale_colour_manual(values = palette, guide = "none") +
    ggplot2::scale_x_continuous(breaks = axis_breaks) +
    ggplot2::coord_cartesian(
      xlim = layout$limits, ylim = y_limits, expand = FALSE
    ) +
    ggplot2::labs(x = layout$xlabel, y = NULL, title = title) +
    ggplot2::theme_light() +
    ggplot2::theme(
      panel.grid = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      legend.position = if (legend) "bottom" else "none",
      plot.title = ggplot2::element_text(face = "bold", size = 11)
    )

  # transcript labels above each row and event labels below the exon they
  # describe, so the two sets cannot collide
  if (transcript_label) {
    p <- p +
      ggplot2::geom_text(
        data = tx_lines,
        ggplot2::aes(
          x = x, y = row_y + 0.6, label = tx_label, colour = direction
        ),
        hjust = 0,
        vjust = 0,
        size = 3,
        fontface = "bold",
        show.legend = FALSE
      )
  }
  if (label_events && any(rects$is_event)) {
    p <- p +
      ggplot2::geom_text(
        data = dplyr::filter(rects, is_event),
        ggplot2::aes(
          x = (plot_start + plot_end) / 2, y = row_y - exon_half_height - 0.06,
          label = event_label
        ),
        vjust = 1,
        size = label_size,
        colour = "grey15"
      )
  }
  # strand arrows rise half an exon box. added last, so the layer does not
  # shift the index of the layers above
  arrows <- tss_arrows(
    layout$exons, tx_rows, layout$limits,
    base = exon_half_height, rise = exon_half_height
  )
  p +
    ggplot2::geom_path(
      data = arrows,
      ggplot2::aes(x = x, y = y, group = tx_id),
      colour = "black",
      linewidth = 0.5,
      linejoin = "mitre",
      arrow = ggplot2::arrow(
        length = ggplot2::unit(1.2, "mm"), type = "closed"
      )
    )
}

#' Plot a per-transcript fold change for the transcripts of splicelogic
#' events
#'
#' Draws one diverging bar per transcript appearing in `tx_id` or
#' `event_tx_id` of `events`: left of zero for a negative value and right for
#' a positive one. It is the companion to [plot_transcripts()]: given the same
#' `events` the two plots share their row order and y limits, so they line up
#' when placed side by side, e.g. with `patchwork`.
#'
#' @inheritParams plot_transcripts
#' @param tx_lfc Numeric vector named by transcript id, e.g. a log2 fold change
#'   from a differential expression analysis. Transcripts not named in it keep
#'   their row but get no bar.
#' @param lfc_max Half-width of the x axis. `NULL` (default) uses the largest
#'   absolute value in the plot; pass a number to make plots comparable.
#'   Values beyond it are clipped at the axis edge.
#' @param lfc_label x-axis title.
#' @param lfc_ends Optional length-2 character vector naming the negative and
#'   positive ends of the axis, e.g. `c("KD", "WT")` for a `log2(WT/KD)`.
#'   Default `NULL` draws no end labels.
#' @param bar_color Colour of the bars. Default `"grey30"`.
#' @param transcript_label Whether to print the transcript ids on the y axis,
#'   for use on its own. Default `FALSE`, as [plot_transcripts()] already
#'   labels the rows.
#'
#' @return A `ggplot` object.
#'
#' @examples
#' exons <- data.frame(
#'   seqnames = "chr1",
#'   start = c(1, 201, 401, 1, 401),
#'   end = c(100, 300, 500, 100, 500),
#'   strand = "+",
#'   gene_id = "g1",
#'   tx_id = c("down", "down", "down", "up", "up"),
#'   exon_rank = c(1, 2, 3, 1, 2),
#'   estimate = c(-1, -1, -1, 1, 1)
#' ) |>
#'   plyranges::as_granges() |>
#'   preprocess(coef_col = "estimate")
#'
#' events <- find_all_events(exons, verbose = FALSE)
#' tx_lfc <- c(down = -1.8, up = 0.6)
#'
#' if (requireNamespace("ggplot2", quietly = TRUE)) {
#'   plot_transcript_lfc(events, tx_lfc, transcript_label = TRUE)
#' }
#'
#' @export
plot_transcript_lfc <- function(
  events,
  tx_lfc,
  title = NULL,
  lfc_max = NULL,
  lfc_label = "log2 fold change",
  lfc_ends = NULL,
  bar_color = "grey30",
  transcript_label = FALSE
) {
  check_ggplot2()
  check_plot_events(events)
  if (!is.numeric(tx_lfc) || is.null(names(tx_lfc))) {
    stop("'tx_lfc' must be a numeric vector named by transcript id.")
  }

  tx_rows <- transcript_rows(events)
  bars <- tx_rows |>
    dplyr::mutate(lfc = unname(tx_lfc[tx_id])) |>
    dplyr::filter(!is.na(lfc))
  if (nrow(bars) == 0L) {
    warning("No transcript in 'events' has a value in 'tx_lfc'.")
  }

  if (is.null(lfc_max)) {
    lfc_max <- if (nrow(bars) > 0L) max(abs(bars$lfc)) else 1
  }
  if (!is.finite(lfc_max) || lfc_max <= 0) {
    lfc_max <- 1
  }
  x_limits <- c(-lfc_max, lfc_max) * 1.05
  y_limits <- row_limits(tx_rows)

  p <- ggplot2::ggplot(bars) +
    # zero line first, so the bars sit on top of it
    ggplot2::geom_vline(xintercept = 0, colour = "grey70", linewidth = 0.3) +
    ggplot2::geom_segment(
      ggplot2::aes(
        x = 0, xend = pmax(pmin(lfc, lfc_max), -lfc_max),
        y = row_y, yend = row_y
      ),
      colour = bar_color,
      linewidth = 1.5,
      lineend = "round"
    ) +
    ggplot2::scale_y_continuous(
      breaks = tx_rows$row_y,
      labels = if (transcript_label) tx_rows$tx_id else NULL
    ) +
    ggplot2::coord_cartesian(
      xlim = x_limits, ylim = y_limits, expand = FALSE
    ) +
    ggplot2::labs(x = lfc_label, y = NULL, title = title) +
    ggplot2::theme_light() +
    ggplot2::theme(
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      plot.title = ggplot2::element_text(face = "bold", size = 11)
    )

  if (!is.null(lfc_ends)) {
    stopifnot(length(lfc_ends) == 2L)
    p <- p +
      ggplot2::annotate(
        "text",
        x = x_limits,
        y = y_limits[1],
        label = lfc_ends,
        hjust = c(0, 1),
        vjust = -0.5,
        size = 2.6,
        colour = "grey45"
      )
  }
  p
}

#' Plot each group of a split event set
#'
#' Skips, with a warning, any group that cannot be laid out, e.g. transcripts
#' on different chromosomes. Each plot is titled by its group, after `title`
#' when one is given.
#' @noRd
plot_event_groups <- function(events_list, exons, title, ...) {
  check_ggplot2()
  group_names <- names(events_list)
  plots <- lapply(stats::setNames(group_names, group_names), function(nm) {
    group_title <- if (is.null(title)) nm else paste(title, nm, sep = ": ")
    tryCatch(
      plot_transcripts(events_list[[nm]], exons, title = group_title, ...),
      error = function(e) {
        warning("Skipping ", nm, ": ", conditionMessage(e))
        NULL
      }
    )
  })
  Filter(Negate(is.null), plots)
}

#' Plot the transcripts involved in splicelogic events, one plot per gene
#'
#' Splits `events` by `gene_id` and draws each gene with
#' [plot_transcripts()].
#'
#' @inheritParams plot_transcripts
#' @param events A GRanges returned by [find_all_events()] or any `find_*()`
#'   function, with a `gene_id` column.
#' @param genes Optional character vector of gene ids to restrict to.
#' @param title Optional prefix for the plot titles, which are otherwise the
#'   gene id.
#' @param ... Passed to [plot_transcripts()].
#'
#' @return A named list of `ggplot` objects, one per gene.
#'
#' @examples
#' exons <- data.frame(
#'   seqnames = "chr1",
#'   start = c(1, 201, 401, 1, 401),
#'   end = c(100, 300, 500, 100, 500),
#'   strand = "+",
#'   gene_id = "g1",
#'   tx_id = c("down", "down", "down", "up", "up"),
#'   exon_rank = c(1, 2, 3, 1, 2),
#'   estimate = c(-1, -1, -1, 1, 1)
#' ) |>
#'   plyranges::as_granges() |>
#'   preprocess(coef_col = "estimate")
#'
#' events <- find_all_events(exons, verbose = FALSE)
#'
#' if (requireNamespace("ggplot2", quietly = TRUE)) {
#'   plots <- plot_transcripts_by_gene(events, exons)
#'   plots[["g1"]]
#' }
#'
#' @export
plot_transcripts_by_gene <- function(events, exons, genes = NULL,
                                     title = NULL, ...) {
  check_plot_events(events, required = "gene_id")
  if (!is.null(genes)) {
    events <- events |>
      dplyr::filter(gene_id %in% genes)
  }
  if (length(events) == 0L) {
    stop("No events left to plot.")
  }
  # split() rather than group_by(): each gene needs its own GRanges
  events_list <- S4Vectors::split(events, as.character(events$gene_id))
  plot_event_groups(events_list, exons, title, ...)
}

#' Plot the transcripts involved in splicelogic events, one plot per pair
#'
#' Splits `events` by transcript pair, so each plot shows two transcripts and
#' every event between them. The pair is unordered, so events reported from
#' either side land in the same plot.
#'
#' @inheritParams plot_transcripts
#' @param events A GRanges returned by [find_all_events()] or any `find_*()`
#'   function. A `tx_pair` column, if present, is used as the grouping as is.
#' @param title Optional prefix for the plot titles, which are otherwise the
#'   transcript pair.
#' @param ... Passed to [plot_transcripts()].
#'
#' @return A named list of `ggplot` objects, one per transcript pair.
#'
#' @examples
#' exons <- data.frame(
#'   seqnames = "chr1",
#'   start = c(1, 201, 401, 1, 401),
#'   end = c(100, 300, 500, 100, 500),
#'   strand = "+",
#'   gene_id = "g1",
#'   tx_id = c("down", "down", "down", "up", "up"),
#'   exon_rank = c(1, 2, 3, 1, 2),
#'   estimate = c(-1, -1, -1, 1, 1)
#' ) |>
#'   plyranges::as_granges() |>
#'   preprocess(coef_col = "estimate")
#'
#' events <- find_all_events(exons, verbose = FALSE)
#'
#' if (requireNamespace("ggplot2", quietly = TRUE)) {
#'   plots <- plot_transcripts_by_pair(events, exons)
#'   plots[["down-up"]]
#' }
#'
#' @export
plot_transcripts_by_pair <- function(events, exons, title = NULL, ...) {
  check_plot_events(events)
  if (!"tx_pair" %in% names(GenomicRanges::mcols(events))) {
    events <- events |>
      dplyr::mutate(
        tx_pair = paste0(
          pmin(tx_id, event_tx_id), "-", pmax(tx_id, event_tx_id)
        )
      )
  }
  # split() rather than group_by(): each pair needs its own GRanges
  events_list <- S4Vectors::split(events, as.character(events$tx_pair))
  plot_event_groups(events_list, exons, title, ...)
}
